"""Feature matrix extraction CLI and documentation builder for Project FORESIGHT."""

from pathlib import Path
import json
from foresight.config.constants import DOCS_DIR, PROCESSED_DATA_DIR
from foresight.data.loader import load_processed_sales
from foresight.features.pipeline import FeatureEngineeringPipeline
from foresight.utils.logger import get_logger

logger = get_logger(__name__)


def generate_feature_dictionary_doc(
    pipeline: FeatureEngineeringPipeline,
    features_df,
    docs_path: Path = DOCS_DIR / "feature_dictionary.md",
) -> None:
    """Generate Markdown documentation cataloging all engineered features."""
    meta = pipeline.get_feature_metadata(features_df)
    docs_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Project FORESIGHT — Feature Dictionary & Engineering Contracts",
        "",
        "This document details the engineered feature space generated by `FeatureEngineeringPipeline` for machine learning demand forecasting.",
        "",
        f"**Total Predictive Features:** `{meta.total_features}`  ",
        f"**Target Column:** `{meta.target_column}`  ",
        f"**Warmup Horizon:** `{meta.warmup_days_required} days`  ",
        "",
        "---",
        "",
        "## 1. Feature Groups & Columns",
        "",
        "### 1.1 Temporal & Calendar Features",
        "| Feature Name | Type | Mathematical Formulation / Description |",
        "| :--- | :--- | :--- |",
        "| `day_of_week` | `int` | Integer day of week ($0 = \\text{Monday}, 6 = \\text{Sunday}$) |",
        "| `day_of_month` | `int` | Day of calendar month ($1 - 31$) |",
        "| `week_of_year` | `int` | ISO calendar week number ($1 - 53$) |",
        "| `month` | `int` | Month number ($1 - 12$) |",
        "| `quarter` | `int` | Fiscal quarter ($1 - 4$) |",
        "| `year` | `int` | Observation calendar year |",
        "| `is_weekend` | `int` | Binary flag ($1$ for Saturday/Sunday, $0$ otherwise) |",
        "| `sin_day_of_week` | `float` | $\\sin(2\\pi \\times \\text{day\\_of\\_week} / 7)$ cyclical encoding |",
        "| `cos_day_of_week` | `float` | $\\cos(2\\pi \\times \\text{day\\_of\\_week} / 7)$ cyclical encoding |",
        "| `sin_month` | `float` | $\\sin(2\\pi \\times (\\text{month}-1) / 12)$ annual cycle encoding |",
        "| `cos_month` | `float` | $\\cos(2\\pi \\times (\\text{month}-1) / 12)$ annual cycle encoding |",
        "",
        "### 1.2 Autoregressive Lag Features",
        "| Feature Name | Type | Historical Retrospective Offset |",
        "| :--- | :--- | :--- |",
        "| `lag_1` | `float` | Actual realized sales $t - 1$ day |",
        "| `lag_7` | `float` | Actual realized sales $t - 7$ days (1-week seasonal) |",
        "| `lag_14` | `float` | Actual realized sales $t - 14$ days (2-week seasonal) |",
        "| `lag_21` | `float` | Actual realized sales $t - 21$ days (3-week seasonal) |",
        "| `lag_28` | `float` | Actual realized sales $t - 28$ days (4-week seasonal) |",
        "| `lag_56` | `float` | Actual realized sales $t - 56$ days (8-week seasonal) |",
        "",
        "### 1.3 Causal Rolling Window Features (Computed on $\\text{shift}(1)$)",
        "| Feature Name | Type | Aggregation Window & Formula |",
        "| :--- | :--- | :--- |",
        "| `rolling_mean_7` | `float` | Mean daily sales over $[t-7, t-1]$ |",
        "| `rolling_std_7` | `float` | Standard deviation of daily sales over $[t-7, t-1]$ |",
        "| `rolling_min_7` | `float` | Minimum daily sales over $[t-7, t-1]$ |",
        "| `rolling_max_7` | `float` | Maximum daily sales over $[t-7, t-1]$ |",
        "| `rolling_mean_14` | `float` | Mean daily sales over $[t-14, t-1]$ |",
        "| `rolling_mean_28` | `float` | Mean daily sales over $[t-28, t-1]$ |",
        "| `rolling_std_28` | `float` | Standard deviation of daily sales over $[t-28, t-1]$ |",
        "| `rolling_min_28` | `float` | Minimum daily sales over $[t-28, t-1]$ |",
        "| `rolling_max_28` | `float` | Maximum daily sales over $[t-28, t-1]$ |",
        "",
        "### 1.4 Velocity & Trend Features",
        "| Feature Name | Type | Description |",
        "| :--- | :--- | :--- |",
        "| `demand_growth_7_28` | `float` | $(\\text{rolling\\_mean\\_7} - \\text{rolling\\_mean\\_28}) / \\text{rolling\\_mean\\_28}$ |",
        "| `rolling_trend_7` | `float` | $(\\text{rolling\\_mean\\_7} - \\text{lag\\_7}) / \\text{lag\\_7}$ |",
        "| `rolling_trend_14` | `float` | $(\\text{rolling\\_mean\\_14} - \\text{lag\\_14}) / \\text{lag\\_14}$ |",
        "| `momentum_7_1` | `float` | $(\\text{lag\\_1} - \\text{lag\\_7}) / \\text{lag\\_7}$ |",
        "",
        "### 1.5 Commercial & Operational Features",
        "| Feature Name | Type | Description |",
        "| :--- | :--- | :--- |",
        "| `discount_percentage`| `float` | $\\max(0, (\\text{unit\\_price} - \\text{price}) / \\text{unit\\_price})$ |",
        "| `price_ratio` | `float` | $\\text{price} / \\text{unit\\_price}$ |",
        "| `is_promoted_int` | `int` | Marketing promotion active flag ($0$ or $1$) |",
        "| `inventory_ratio` | `float` | Current physical stock / recent 7-day velocity |",
        "| `days_of_inventory` | `float` | Estimated stock coverage in days |",
        "| `category_code` | `int` | Label-encoded product category |",
        "| `store_code` | `int` | Label-encoded store / location |",
        "| `sku_code` | `int` | Label-encoded SKU ID |",
        "",
        "---",
        "",
        "## 2. Zero-Leakage Guarantee",
        "",
        "All lag and rolling operators are strictly backward-looking. For any prediction at time $t$:",
        "$$\\mathbf{X}_t = f\\left(y_{t-1}, y_{t-2}, \\dots, y_{t-56}, \\text{calendar}(t), \\text{commercial}(t)\\right)$$",
        "Under no circumstances is $y_t$ or any $y_{t+k}$ accessible during feature calculation.",
    ]

    with open(docs_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    logger.info(f"Saved feature dictionary documentation to {docs_path}")


def build_and_save_features(
    processed_dir: Path = PROCESSED_DATA_DIR,
) -> None:
    """Load processed sales data, transform into engineered feature matrix, and persist."""
    df = load_processed_sales(processed_dir)
    pipeline = FeatureEngineeringPipeline(dropna_warmup=True)

    features_df = pipeline.fit_transform(df)

    parquet_path = processed_dir / "features_engineered.parquet"
    csv_path = processed_dir / "features_engineered.csv"

    features_df.to_parquet(parquet_path, index=False)
    features_df.to_csv(csv_path, index=False)

    generate_feature_dictionary_doc(pipeline, features_df)
    logger.info(f"Saved features matrix to {parquet_path} ({len(features_df):,} rows, {len(features_df.columns)} cols)")


if __name__ == "__main__":
    build_and_save_features()
