"""Forecast Record ORM model."""

from datetime import date, datetime
from sqlalchemy import Date, DateTime, Float, ForeignKey, Integer, String, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from foresight.database.base import Base


class ForecastRecord(Base):
    """Point forecasts and prediction bounds generated by forecasting engines."""
    __tablename__ = "forecast_records"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    sku_id: Mapped[str] = mapped_column(String(50), ForeignKey("products.sku_id"), nullable=False, index=True)
    store_id: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    forecast_date: Mapped[date] = mapped_column(Date, nullable=False, index=True, comment="Date when forecast was created")
    prediction_date: Mapped[date] = mapped_column(Date, nullable=False, index=True, comment="Future date being predicted")
    predicted_demand: Mapped[float] = mapped_column(Float, nullable=False)
    p10_lower_bound: Mapped[float | None] = mapped_column(Float, nullable=True)
    p90_upper_bound: Mapped[float | None] = mapped_column(Float, nullable=True)
    model_name: Mapped[str] = mapped_column(String(100), default="XGBoost")
    model_version: Mapped[str] = mapped_column(String(50), default="1.0.0")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    product = relationship("Product", back_populates="forecasts")

    def __repr__(self) -> str:
        return f"<ForecastRecord(sku='{self.sku_id}', target_date='{self.prediction_date}', pred={self.predicted_demand:.1f})>"
